name: 'Bicep: main-option-7'

on:
  push:
    branches: [main]
    paths:
      - 'options-infra/main-option-7.bicep'
      - 'options-infra/modules/**'
      - '.github/workflows/bicep-validate-reusable.yml'
  pull_request:
    branches: [main]
    paths:
      - 'options-infra/main-option-7.bicep'
      - 'options-infra/modules/**'
      - '.github/workflows/bicep-validate-reusable.yml'

jobs:
  validate:
    uses: ./.github/workflows/bicep-validate-reusable.yml
    with:
      bicep-file: main-option-7.bicep
      working-directory: options-infra
