name: 'Bicep: landing-zone'

on:
  push:
    branches: [main]
    paths:
      - 'options-infra/landing-zone.bicep'
      - 'options-infra/modules/**'
      - '.github/workflows/bicep-validate-reusable.yml'
  pull_request:
    branches: [main]
    paths:
      - 'options-infra/landing-zone.bicep'
      - 'options-infra/modules/**'
      - '.github/workflows/bicep-validate-reusable.yml'

jobs:
  validate:
    uses: ./.github/workflows/bicep-validate-reusable.yml
    with:
      bicep-file: landing-zone.bicep
      working-directory: options-infra
